config/routes.rb
Quoter::Application.routes.draw do
  resources :analyses

  resources :books

  resources :quotes

end

app/models/analysis.rb
class Analysis < ActiveRecord::Base
  attr_accessible :quote_id, :text
  belongs_to :quote
end

app/models/book.rb
class Book < ActiveRecord::Base
  attr_accessible :author, :link_to_book, :title, :year
  has_many :quotes
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :text, :page, :book_id, :analyses_attributes
  belongs_to :book
  has_many :analyses
  accepts_nested_attributes_for :analyses, allow_destroy: true
end

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  def index
    @quotes = Quote.all
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = Quote.new(params[:quote])
    if @quote.save
      redirect_to @quotes
    end
  end
end

app/helpers/analyses_helper.rb
module AnalysesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quoter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/index.html.erb
<div class="center">
<h1>Quoter!</h1>

<%= form_tag("/search", :method => "get") do %>
  <%= label_tag(:q, "Search for Quote:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

<%= link_to("+ Add A Quote", new_quote_path) %>


<table>
  <tr>
    <th>Book Title</th>
    <th>Year</th>
    <th>Author</th>
    <th>Quote</th>
    <th>Page</th>
    <th>Analysis</th>
  </tr>

  <% @quotes.each do |quote| %>
  <tr>
    <td><%= quote.book.title %></td>
    <td><%= quote.book.year %></td>
    <td><%= quote.book.author %></td>
    <td><%= truncate quote.text, length: 60 %></td>
    <td><%= quote.page %></td>
    <td><% quote.analyses.each do |analysis| %> 
          <%= truncate analysis.text, length: 60 %>
    <% end %>
    </td>
  </tr>
  <% end %>

  

</table>
</div>

app/views/quotes/new.html.erb
<%= form_for @quote do |f| %>
  <% if @quote.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>
      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text, "Quote" %><br />
    <%= f.text_field :text %>
  </div>

  <%= f.fields_for :analysis do |f| %>
    <%= f.label :text, "Analysis of Quote" %><br />
    <%= f.text_field :text %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>